<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="given_files\**" />
      <Compile Remove="NewDirectory1\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="given_files\**" />
      <EmbeddedResource Remove="NewDirectory1\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="given_files\**" />
      <None Remove="NewDirectory1\**" />
    </ItemGroup>

</Project>
